import { AppLayout } from "@/components/layout/AppLayout";
import { PageHeader } from "@/components/shared/DataWidgets";
import { summaries } from "@/data/mockData";
import { FileText, Copy, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";

export default function Summaries() {
  const { toast } = useToast();

  return (
    <AppLayout>
      <PageHeader title="AI Executive Summaries" subtitle="GPT-4o powered policy briefs and allocation recommendations" />

      <div className="space-y-6">
        {summaries.map(s => (
          <div key={s.id} className="bg-card rounded-lg border p-6">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <FileText className="w-4 h-4 text-primary" />
                <span className="text-sm font-semibold">
                  {s.report_type === "DISTRICT" ? `District Report: ${s.district_name}` : "National Assessment"}
                </span>
                <span className="govt-badge bg-primary/10 text-primary">{s.report_type}</span>
              </div>
              <div className="flex gap-2">
                <Button variant="outline" size="sm" onClick={() => {
                  navigator.clipboard.writeText(s.summary_text);
                  toast({ title: "Copied to clipboard" });
                }}>
                  <Copy className="w-3 h-3 mr-1" /> Copy
                </Button>
                <Button variant="outline" size="sm"><Download className="w-3 h-3 mr-1" /> PDF</Button>
              </div>
            </div>
            <div className="prose prose-sm max-w-none text-sm text-foreground leading-relaxed whitespace-pre-line">
              {s.summary_text.split("\n\n").map((para, i) => (
                <p key={i} className="mb-3">{para.replace(/\*\*/g, "")}</p>
              ))}
            </div>
            <div className="mt-4 pt-3 border-t flex items-center gap-4 text-xs text-muted-foreground">
              <span>Generated by: {s.generated_by}</span>
              <span>Date: {new Date(s.createdAt).toLocaleDateString("en-IN")}</span>
            </div>
          </div>
        ))}
      </div>
    </AppLayout>
  );
}
