import { useState } from "react";
import { AppLayout } from "@/components/layout/AppLayout";
import { PageHeader, formatCrores } from "@/components/shared/DataWidgets";
import { summaries, districts, generateDistrictSummary, generateStateSummary } from "@/data/mockData";
import { useAppStore } from "@/store/appStore";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { FileText, Copy, Download, Loader2, RefreshCw, Plus } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export default function Summaries() {
  const { toast } = useToast();
  const canCompute = useAppStore(s => s.canCompute());
  const [typeFilter, setTypeFilter] = useState("ALL");
  const [generatingState, setGeneratingState] = useState(false);
  const [generatingDistrict, setGeneratingDistrict] = useState<string | null>(null);
  const [selectedSummary, setSelectedSummary] = useState<string | null>(null);
  const [, setRefresh] = useState(0);

  const filtered = summaries.filter(s => {
    if (typeFilter === "DISTRICT" && s.summary_type !== "DISTRICT") return false;
    if (typeFilter === "STATE" && s.summary_type !== "STATE") return false;
    return true;
  });

  const detail = selectedSummary ? summaries.find(s => s.id === selectedSummary) : null;

  const handleGenerateState = () => {
    setGeneratingState(true);
    setTimeout(() => {
      generateStateSummary();
      setGeneratingState(false);
      setRefresh(r => r + 1);
      toast({ title: "State Summary Generated", description: "Gujarat Health state-level policy brief created." });
    }, 2000);
  };

  const handleGenerateDistrict = (districtId: string) => {
    setGeneratingDistrict(districtId);
    setTimeout(() => {
      generateDistrictSummary(districtId);
      setGeneratingDistrict(null);
      setRefresh(r => r + 1);
      toast({ title: "District Summary Generated" });
    }, 1500);
  };

  if (detail) {
    return (
      <AppLayout>
        <Button variant="ghost" size="sm" onClick={() => setSelectedSummary(null)} className="mb-4">
          ← Back to Summaries
        </Button>
        <div className="max-w-4xl">
          <div className="flex items-center gap-3 mb-4">
            <h1 className="text-xl font-bold font-serif">
              {detail.summary_type === "DISTRICT" ? `${detail.district_name} Health Brief` : "Gujarat State Health Overview"}
            </h1>
            <span className={`govt-badge ${detail.summary_type === "DISTRICT" ? "bg-blue-100 text-blue-700" : "bg-amber-100 text-amber-700"}`}>
              {detail.summary_type}
            </span>
          </div>

          <div className="flex gap-4 mb-4 text-xs text-muted-foreground">
            <span>Generated by: {detail.generated_by}</span>
            <span>Type: {detail.summary_type}</span>
            <span>Sector: Health</span>
            <span>Period: Q{detail.quarter} {detail.year}</span>
            <span>Date: {new Date(detail.createdAt).toLocaleDateString("en-IN")}</span>
          </div>

          <div className="space-y-4 mb-6">
            <div className="p-5 bg-red-50 rounded-lg border border-red-100">
              <p className="text-xs font-bold text-red-700 mb-2">🔴 PROBLEM</p>
              <p className="text-sm leading-relaxed" style={{ fontFamily: "'Source Serif 4', Georgia, serif" }}>{detail.problem_text}</p>
            </div>
            <div className="p-5 bg-blue-50 rounded-lg border border-blue-100">
              <p className="text-xs font-bold text-blue-700 mb-2">🔍 ANALYSIS</p>
              <p className="text-sm leading-relaxed" style={{ fontFamily: "'Source Serif 4', Georgia, serif" }}>{detail.analysis_text}</p>
            </div>
            <div className="p-5 bg-green-50 rounded-lg border border-green-100">
              <p className="text-xs font-bold text-green-700 mb-2">✅ RECOMMENDATION</p>
              <p className="text-sm leading-relaxed" style={{ fontFamily: "'Source Serif 4', Georgia, serif" }}>{detail.recommendation_text}</p>
            </div>
          </div>

          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={() => {
              const text = `PROBLEM:\n${detail.problem_text}\n\nANALYSIS:\n${detail.analysis_text}\n\nRECOMMENDATION:\n${detail.recommendation_text}`;
              navigator.clipboard.writeText(text);
              toast({ title: "Copied to clipboard" });
            }}>
              <Copy className="w-3 h-3 mr-1" /> Copy Summary
            </Button>
            <Button variant="outline" size="sm">
              <Download className="w-3 h-3 mr-1" /> Download PDF
            </Button>
            {canCompute && (
              <Button variant="outline" size="sm" onClick={() => {
                if (detail.summary_type === "STATE") handleGenerateState();
                else if (detail.districtId) handleGenerateDistrict(detail.districtId);
              }}>
                <RefreshCw className="w-3 h-3 mr-1" /> Regenerate
              </Button>
            )}
          </div>
        </div>
      </AppLayout>
    );
  }

  return (
    <AppLayout>
      <div className="flex items-center justify-between mb-6">
        <PageHeader title="AI Executive Summaries" subtitle="Bedrock-powered IAS-grade policy briefs for Gujarat Health" />
        {canCompute && (
          <Button onClick={handleGenerateState} disabled={generatingState}>
            {generatingState ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Plus className="w-4 h-4 mr-2" />}
            Generate State Summary
          </Button>
        )}
      </div>

      {/* Filters */}
      <div className="flex gap-3 mb-4">
        <Select value={typeFilter} onValueChange={setTypeFilter}>
          <SelectTrigger className="w-36"><SelectValue /></SelectTrigger>
          <SelectContent>
            <SelectItem value="ALL">All Types</SelectItem>
            <SelectItem value="DISTRICT">District</SelectItem>
            <SelectItem value="STATE">State</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {/* Card Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {filtered.map(s => (
          <div key={s.id} className="bg-card rounded-lg border p-5 hover:shadow-md transition-shadow">
            <div className="flex items-center gap-2 mb-3">
              <FileText className="w-4 h-4 text-primary" />
              <span className={`govt-badge ${s.summary_type === "DISTRICT" ? "bg-blue-100 text-blue-700" : "bg-amber-100 text-amber-700"}`}>
                {s.summary_type}
              </span>
              <span className="text-sm font-semibold flex-1">
                {s.summary_type === "DISTRICT" ? `${s.district_name} Health Brief` : "Gujarat State Health Overview"}
              </span>
            </div>
            <p className="text-xs text-muted-foreground mb-2">
              Q{s.quarter} {s.year} • {s.generated_by} • {new Date(s.createdAt).toLocaleDateString("en-IN")}
            </p>
            <p className="text-sm text-foreground line-clamp-3 mb-3">{s.problem_text}</p>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={() => setSelectedSummary(s.id)}>View Full</Button>
              <Button variant="outline" size="sm"><Download className="w-3 h-3 mr-1" /> PDF</Button>
            </div>
          </div>
        ))}
      </div>

      {filtered.length === 0 && (
        <div className="text-center py-12">
          <FileText className="w-12 h-12 text-muted-foreground mx-auto mb-3" />
          <p className="text-muted-foreground">No summaries generated yet.</p>
        </div>
      )}
    </AppLayout>
  );
}
